export const API_BASE_URL = "https://health.googleapis.com/v4";
export const CHARACTER_LIMIT = 25000;

export const DATA_TYPES = [
  "active-energy-burned",
  "active-minutes",
  "active-zone-minutes",
  "activity-level",
  "altitude",
  "blood-glucose",
  "body-fat",
  "calories-in-heart-rate-zone",
  "core-body-temperature",
  "daily-heart-rate-variability",
  "daily-heart-rate-zones",
  "daily-oxygen-saturation",
  "daily-respiratory-rate",
  "daily-resting-heart-rate",
  "daily-sleep-temperature-derivations",
  "daily-vo2-max",
  "distance",
  "electrocardiogram",
  "elevation",
  "exercise",
  "floors",
  "food",
  "food-measurement-unit",
  "heart-rate",
  "heart-rate-variability",
  "height",
  "hydration-log",
  "irregular-rhythm-notification",
  "nutrition-log",
  "oxygen-saturation",
  "respiratory-rate-sleep-summary",
  "run-vo2-max",
  "sedentary-period",
  "sleep",
  "steps",
  "swim-lengths-data",
  "time-in-heart-rate-zone",
  "total-calories",
  "vo2-max",
  "weight",
] as const;

export type DataType = (typeof DATA_TYPES)[number];
